// Generated by @ts-kizuna/swift. Do not edit by hand.

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

public enum API {

    /// A user in the system
    public struct User: Codable, Sendable, Equatable {
        /// Unique user identifier
        public let id: String
        /// Display name
        public let name: String
        /// Email address
        @available(*, deprecated, message: "use `email_address` instead.")
        public let email: String
        /// Email address
        public let email_address: String?
        /// Family name on the wire as `last_name` — exercises snake_case fidelity through the generators.
        public let last_name: String?

        public init(
            id: String,
            name: String,
            email: String,
            email_address: String? = nil,
            last_name: String? = nil
        ) {
            self.id = id
            self.name = name
            self.email = email
            self.email_address = email_address
            self.last_name = last_name
        }
    }

    /// RFC 9457 Problem Details error response.
    public struct ProblemDetails: Codable, Sendable, Equatable {
        public let type: String
        public let title: String
        public let status: Int
        public let detail: String

        public init(
            type: String,
            title: String,
            status: Int,
            detail: String
        ) {
            self.type = type
            self.title = title
            self.status = status
            self.detail = detail
        }
    }

    public struct CreateUserInput: Codable, Sendable, Equatable {
        /// Display name
        public let name: String
        /// Email address
        public let email: String
        /// Family name. Snake_case wire key, kept verbatim by both clients.
        public let last_name: String?

        public init(
            name: String,
            email: String,
            last_name: String? = nil
        ) {
            self.name = name
            self.email = email
            self.last_name = last_name
        }
    }

    public enum NotificationEvent: Codable, Sendable, Equatable {
        case email(EmailEvent)
        case sms(SmsEvent)

        private enum DiscriminatorKey: String, CodingKey {
            case discriminator = "channel"
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: DiscriminatorKey.self)
            let kind = try container.decode(String.self, forKey: .discriminator)
            let single = try decoder.singleValueContainer()
            switch kind {
            case "email":
                self = .email(try single.decode(EmailEvent.self))
            case "sms":
                self = .sms(try single.decode(SmsEvent.self))
            default:
                throw DecodingError.dataCorruptedError(forKey: .discriminator, in: container, debugDescription: "Unknown discriminator: \(kind)")
            }
        }

        public func encode(to encoder: Encoder) throws {
            var single = encoder.singleValueContainer()
            switch self {
            case .email(let payload):
                try single.encode(payload)
            case .sms(let payload):
                try single.encode(payload)
            }
        }
    }

    public struct EmailEvent: Codable, Sendable, Equatable {
        public let channel: String
        public let to: String
        public let subject: String

        public init(
            channel: String,
            to: String,
            subject: String
        ) {
            self.channel = channel
            self.to = to
            self.subject = subject
        }
    }

    public struct SmsEvent: Codable, Sendable, Equatable {
        public let channel: String
        public let phone: String
        public let text: String

        public init(
            channel: String,
            phone: String,
            text: String
        ) {
            self.channel = channel
            self.phone = phone
            self.text = text
        }
    }

    public struct EventRecord: Codable, Sendable, Equatable {

        public enum Kind: String, Codable, Sendable {
            case login = "login"
            case logout = "logout"
            case signup = "signup"
        }
        public let id: String
        public let kind: Kind
        public let occurredAt: Date
        public let userId: String

        public init(
            id: String,
            kind: Kind,
            occurredAt: Date,
            userId: String
        ) {
            self.id = id
            self.kind = kind
            self.occurredAt = occurredAt
            self.userId = userId
        }
    }
}

public actor APIClient {

    public struct MultipartFile: Sendable, Equatable {
        public let data: Foundation.Data
        public let filename: String
        public let mimeType: String

        public init(data: Data, filename: String, mimeType: String = "application/octet-stream") {
            self.data = data
            self.filename = filename
            self.mimeType = mimeType
        }
    }

    public struct ValidationError: Codable, Sendable, Equatable {
        public let type: String
        public let title: String
        public let status: Int
        public let detail: String
        public let errors: [ValidationIssue]

        public init(type: String, title: String, status: Int, detail: String, errors: [ValidationIssue]) {
            self.type = type
            self.title = title
            self.status = status
            self.detail = detail
            self.errors = errors
        }
    }

    public struct ValidationIssue: Codable, Sendable, Equatable {
        public let code: String
        public let path: [String]
        public let message: String

        public init(code: String, path: [String], message: String) {
            self.code = code
            self.path = path
            self.message = message
        }
    }

    public struct AnyCodable: Codable, Sendable, Equatable {
        public let value: Foundation.Data?
        public init(value: Foundation.Data? = nil) { self.value = value }
        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if container.decodeNil() { self.value = nil; return }
            let raw = try JSONSerialization.data(withJSONObject: try container.decode(CodableValue.self).rawValue, options: [])
            self.value = raw
        }
        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            if let value = value, let object = try? JSONSerialization.jsonObject(with: value) {
                try container.encode(CodableValue(rawValue: object))
            } else {
                try container.encodeNil()
            }
        }
        public static func == (lhs: AnyCodable, rhs: AnyCodable) -> Bool { lhs.value == rhs.value }

        private struct CodableValue: Codable {
            let rawValue: Any
            init(rawValue: Any) { self.rawValue = rawValue }
            init(from decoder: Decoder) throws {
                let container = try decoder.singleValueContainer()
                if container.decodeNil() { self.rawValue = NSNull(); return }
                if let value = try? container.decode(Bool.self) { self.rawValue = value; return }
                if let value = try? container.decode(Int.self) { self.rawValue = value; return }
                if let value = try? container.decode(Double.self) { self.rawValue = value; return }
                if let value = try? container.decode(String.self) { self.rawValue = value; return }
                if let value = try? container.decode([CodableValue].self) { self.rawValue = value.map(\.rawValue); return }
                if let value = try? container.decode([String: CodableValue].self) { self.rawValue = value.mapValues(\.rawValue); return }
                self.rawValue = NSNull()
            }
            func encode(to encoder: Encoder) throws {
                var container = encoder.singleValueContainer()
                switch rawValue {
                case is NSNull: try container.encodeNil()
                case let value as Bool: try container.encode(value)
                case let value as Int: try container.encode(value)
                case let value as Double: try container.encode(value)
                case let value as String: try container.encode(value)
                case let value as [Any]: try container.encode(value.map(CodableValue.init(rawValue:)))
                case let value as [String: Any]: try container.encode(value.mapValues(CodableValue.init(rawValue:)))
                default: try container.encodeNil()
                }
            }
        }
    }
    public let baseURL: URL
    public let session: URLSession
    public nonisolated let timeout: TimeInterval
    public var requestMiddleware: (@Sendable (inout URLRequest) async throws -> Void)?
    public var responseMiddleware: (@Sendable (URLRequest, Foundation.Data, URLResponse) async -> Void)?
    private let encoder: JSONEncoder
    private let decoder: JSONDecoder

    public init(baseURL: URL, session: URLSession = .shared, timeout: TimeInterval = 30, requestMiddleware: (@Sendable (inout URLRequest) async throws -> Void)? = nil, responseMiddleware: (@Sendable (URLRequest, Foundation.Data, URLResponse) async -> Void)? = nil) {
        self.baseURL = baseURL
        self.session = session
        self.timeout = timeout
        self.requestMiddleware = requestMiddleware
        self.responseMiddleware = responseMiddleware
        self.encoder = Kizuna.makeJSONEncoder()
        self.decoder = Kizuna.makeJSONDecoder()
    }

    func _kizunaContext() -> (URL, URLSession, JSONEncoder, JSONDecoder, (@Sendable (inout URLRequest) async throws -> Void)?, (@Sendable (URLRequest, Foundation.Data, URLResponse) async -> Void)?) {
        return (baseURL, session, encoder, decoder, requestMiddleware, responseMiddleware)
    }

    public var users: APIUsersClient {
        APIUsersClient(_actor: self)
    }

    public var health: APIHealthClient {
        APIHealthClient(_actor: self)
    }

    public enum SendNotification {

        public struct Response202: Codable, Sendable, Equatable {
            public let accepted: Bool

            public init(accepted: Bool) {
                self.accepted = accepted
            }
        }

        public struct Result: Sendable {
            public let body: Response202
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case badRequest(APIClient.ValidationError)
        }
    }

    public enum ListEvents {

        public enum QueryKind: String, Codable, Sendable {
            case login = "login"
            case logout = "logout"
            case signup = "signup"
        }

        public struct Response: Codable, Sendable, Equatable {
            public let events: [API.EventRecord]
            public let echo: ResponseEcho

            public init(
                events: [API.EventRecord],
                echo: ResponseEcho
            ) {
                self.events = events
                self.echo = echo
            }
        }

        public struct ResponseEcho: Codable, Sendable, Equatable {
            public let since: Date?
            public let kind: ResponseEchoKind?
            public let ids: [String]?
            public let label: String?
            public let tagIds: [String]?

            public init(
                since: Date? = nil,
                kind: ResponseEchoKind? = nil,
                ids: [String]? = nil,
                label: String? = nil,
                tagIds: [String]? = nil
            ) {
                self.since = since
                self.kind = kind
                self.ids = ids
                self.label = label
                self.tagIds = tagIds
            }
        }

        public enum ResponseEchoKind: String, Codable, Sendable {
            case login = "login"
            case logout = "logout"
            case signup = "signup"
        }

        public struct Result: Sendable {
            public let body: Response
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case badRequest(APIClient.ValidationError)
        }
    }

    public enum ValidateConfig {

        public struct Input: Codable, Sendable, Equatable {
            public let `default`: String
            public let interval: Int

            private enum CodingKeys: String, CodingKey {
                case `default`
                case interval
            }

            public init(
                `default`: String,
                interval: Int
            ) {
                self.`default` = `default`
                self.interval = interval
            }
        }

        /// Validation result
        public struct Response: Codable, Sendable, Equatable {
            public let status: String

            public init(status: String) {
                self.status = status
            }
        }

        public struct Result: Sendable {
            public let body: Response
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case badRequest(API.ProblemDetails)
            case unauthorized
            case validationError(APIClient.ValidationError)
        }
    }

    public enum Webhook {

        public struct Response: Codable, Sendable, Equatable {
            public let received: Bool

            public init(received: Bool) {
                self.received = received
            }
        }

        public struct Result: Sendable {
            public let body: Response
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case badRequest(APIClient.ValidationError)
        }
    }

    public enum UsersListUsers {

        public struct Response: Codable, Sendable, Equatable {
            public let users: [API.User]
            public let total: Double

            public init(
                users: [API.User],
                total: Double
            ) {
                self.users = users
                self.total = total
            }
        }

        public struct Result: Sendable {
            public let body: Response
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case badRequest(APIClient.ValidationError)
        }
    }

    public enum UsersSearchUsers {

        public struct Response: Codable, Sendable, Equatable {
            public let users: [API.User]
            public let nextCursor: Double?

            public init(
                users: [API.User],
                nextCursor: Double? = nil
            ) {
                self.users = users
                self.nextCursor = nextCursor
            }
        }

        public struct Result: Sendable {
            public let body: Response
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case badRequest(APIClient.ValidationError)
        }
    }

    public enum UsersGetUser {

        public struct Result: Sendable {
            public let body: API.User
            public let headers: Headers

            public struct Headers: Sendable {
                public let xRequestId: String?
            }
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case notFound(API.ProblemDetails)
        }
    }

    public enum UsersCreateUser {

        public struct Result: Sendable {
            public let body: API.User
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case badRequest(API.ProblemDetails)
            case validationError(APIClient.ValidationError)
        }
    }

    public enum UsersDeleteUser {

        public struct Response: Codable, Sendable, Equatable {
            public let success: Bool

            public init(success: Bool) {
                self.success = success
            }
        }

        public struct Result: Sendable {
            public let body: Response
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case notFound(API.ProblemDetails)
        }
    }

    public enum UsersArchiveUser {

        public struct Response: Codable, Sendable, Equatable {
            public let alreadyArchived: Bool
            public let userId: String

            public init(
                alreadyArchived: Bool,
                userId: String
            ) {
                self.alreadyArchived = alreadyArchived
                self.userId = userId
            }
        }

        public struct Response201: Codable, Sendable, Equatable {
            public let archivedAt: Date
            public let userId: String

            public init(
                archivedAt: Date,
                userId: String
            ) {
                self.archivedAt = archivedAt
                self.userId = userId
            }
        }

        public enum Success: Sendable, Equatable {
            case status200(Response)
            case status201(Response201)
        }

        public struct Result: Sendable {
            public let body: Success
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
        }
    }

    public enum UsersUploadAvatar {

        public struct Input: Sendable, Equatable {
            public let file: APIClient.MultipartFile
            public let userId: String

            public init(
                file: APIClient.MultipartFile,
                userId: String
            ) {
                self.file = file
                self.userId = userId
            }
        }

        public struct Response: Codable, Sendable, Equatable {
            public let size: Double
            public let userId: String

            public init(
                size: Double,
                userId: String
            ) {
                self.size = size
                self.userId = userId
            }
        }

        public struct Result: Sendable {
            public let body: Response
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case badRequest(APIClient.ValidationError)
        }
    }

    public enum UsersPingUser {

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case badRequest(APIClient.ValidationError)
        }
    }

    public enum UsersGetMyWork {

        public struct Response: Codable, Sendable, Equatable {
            public let items: [String]
            public let contentType: ResponseContentType

            public init(
                items: [String],
                contentType: ResponseContentType
            ) {
                self.items = items
                self.contentType = contentType
            }
        }

        public enum ResponseContentType: String, Codable, Sendable {
            case imageJpeg = "image/jpeg"
            case textPlain = "text-plain"
            case videoMp4 = "video.mp4"
            case _3dModel = "3d-model"
        }

        public enum Success: Sendable, Equatable {
            case status200(Response)
            case status204
        }

        public struct Result: Sendable {
            public let body: Success
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
        }
    }

    public enum UsersCheckUser {

        public struct Response: Codable, Sendable, Equatable {
            public let exists: Bool

            public init(exists: Bool) {
                self.exists = exists
            }
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
            case notFound(API.ProblemDetails)
        }
    }

    public enum UsersDescribeUsers {

        public struct Response: Codable, Sendable, Equatable {
            public let allow: String

            public init(allow: String) {
                self.allow = allow
            }
        }

        public struct Result: Sendable {
            public let body: Response
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
        }
    }

    public enum HealthCheck {

        public struct Response: Codable, Sendable, Equatable {
            public let ok: Bool

            public init(ok: Bool) {
                self.ok = ok
            }
        }

        public struct Result: Sendable {
            public let body: Response
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
        }
    }

    public enum HealthVersion {

        public struct Response: Codable, Sendable, Equatable {
            public let version: String

            public init(version: String) {
                self.version = version
            }
        }

        public struct Result: Sendable {
            public let body: Response
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
        }
    }

    public enum HealthHistory {

        public struct ResponseItem: Codable, Sendable, Equatable {
            public let ok: Bool
            public let checkedAt: Date

            public init(
                ok: Bool,
                checkedAt: Date
            ) {
                self.ok = ok
                self.checkedAt = checkedAt
            }
        }

        public struct Result: Sendable {
            public let body: [ResponseItem]
        }

        public enum Failure: Swift.Error, Sendable {
            case requestFailed(Swift.Error)
            case cancelled
            case decoding(Swift.Error, statusCode: Int, data: Foundation.Data)
            case unexpectedStatus(Int, Foundation.Data)
        }
    }

    /// Send a notification (discriminated by channel)
    public func sendNotification(_ input: API.NotificationEvent) async throws(APIClient.SendNotification.Failure) -> APIClient.SendNotification.Result {
        let path = "/notifications"
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.SendNotification.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.SendNotification.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        do {
            request.httpBody = try encoder.encode(input)
        } catch { throw APIClient.SendNotification.Failure.requestFailed(error) }
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.SendNotification.Failure.cancelled }
            catch { throw APIClient.SendNotification.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.SendNotification.Failure.cancelled }
        catch { throw APIClient.SendNotification.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 202:
            do {
                let body = try decoder.decode(APIClient.SendNotification.Response202.self, from: data)
                return APIClient.SendNotification.Result(body: body)
            } catch {
                throw APIClient.SendNotification.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 400:
            do {
                let payload = try decoder.decode(APIClient.ValidationError.self, from: data)
                throw APIClient.SendNotification.Failure.badRequest(payload)
            } catch let error as APIClient.SendNotification.Failure {
                throw error
            } catch {
                throw APIClient.SendNotification.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.SendNotification.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// List events — exercises Date / enum / array query params
    public func listEvents(since: Date? = nil, kind: APIClient.ListEvents.QueryKind? = nil, ids: [String]? = nil, label: String? = nil, tagIds: [String]? = nil) async throws(APIClient.ListEvents.Failure) -> APIClient.ListEvents.Result {
        let path = "/events"
        guard var components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.ListEvents.Failure.unexpectedStatus(-1, Data())
        }
        var queryItems: [URLQueryItem] = []
        if let value = since {
            for stringValue in Kizuna.stringifyQueryValue(value) {
                queryItems.append(URLQueryItem(name: "since", value: stringValue))
            }
        }
        if let value = kind {
            for stringValue in Kizuna.stringifyQueryValue(value) {
                queryItems.append(URLQueryItem(name: "kind", value: stringValue))
            }
        }
        if let value = ids {
            for stringValue in Kizuna.stringifyQueryValue(value) {
                queryItems.append(URLQueryItem(name: "ids", value: stringValue))
            }
        }
        if let value = label {
            for stringValue in Kizuna.stringifyQueryValue(value) {
                queryItems.append(URLQueryItem(name: "label", value: stringValue))
            }
        }
        if let value = tagIds {
            for stringValue in Kizuna.stringifyQueryValue(value) {
                queryItems.append(URLQueryItem(name: "tagIds", value: stringValue))
            }
        }
        if !queryItems.isEmpty { components.queryItems = queryItems }
        guard let url = components.url else { throw APIClient.ListEvents.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "GET"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.ListEvents.Failure.cancelled }
            catch { throw APIClient.ListEvents.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.ListEvents.Failure.cancelled }
        catch { throw APIClient.ListEvents.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(APIClient.ListEvents.Response.self, from: data)
                return APIClient.ListEvents.Result(body: body)
            } catch {
                throw APIClient.ListEvents.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 400:
            do {
                let payload = try decoder.decode(APIClient.ValidationError.self, from: data)
                throw APIClient.ListEvents.Failure.badRequest(payload)
            } catch let error as APIClient.ListEvents.Failure {
                throw error
            } catch {
                throw APIClient.ListEvents.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.ListEvents.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Validate config — exercises generator bug coverage
    public func validateConfig(`default`: String, interval: Int) async throws(APIClient.ValidateConfig.Failure) -> APIClient.ValidateConfig.Result {
        let path = "/config/validate"
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.ValidateConfig.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.ValidateConfig.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        let body = APIClient.ValidateConfig.Input(default: `default`, interval: interval)
        do {
            request.httpBody = try encoder.encode(body)
        } catch { throw APIClient.ValidateConfig.Failure.requestFailed(error) }
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.ValidateConfig.Failure.cancelled }
            catch { throw APIClient.ValidateConfig.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.ValidateConfig.Failure.cancelled }
        catch { throw APIClient.ValidateConfig.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(APIClient.ValidateConfig.Response.self, from: data)
                return APIClient.ValidateConfig.Result(body: body)
            } catch {
                throw APIClient.ValidateConfig.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 400:
            do {
                let payload = try decoder.decode(API.ProblemDetails.self, from: data)
                throw APIClient.ValidateConfig.Failure.badRequest(payload)
            } catch let error as APIClient.ValidateConfig.Failure {
                throw error
            } catch {}
            do {
                let payload = try decoder.decode(APIClient.ValidationError.self, from: data)
                throw APIClient.ValidateConfig.Failure.validationError(payload)
            } catch let error as APIClient.ValidateConfig.Failure {
                throw error
            } catch {}
            throw APIClient.ValidateConfig.Failure.decoding(DecodingError.dataCorrupted(.init(codingPath: [], debugDescription: "No matching type for status 400")), statusCode: statusCode, data: data)
        case 401:
            throw APIClient.ValidateConfig.Failure.unauthorized
        default:
            throw APIClient.ValidateConfig.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Receive arbitrary webhook payload — exercises z.any() / AnyCodable codegen
    public func webhook(_ input: APIClient.AnyCodable) async throws(APIClient.Webhook.Failure) -> APIClient.Webhook.Result {
        let path = "/webhook"
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.Webhook.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.Webhook.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        do {
            request.httpBody = try encoder.encode(input)
        } catch { throw APIClient.Webhook.Failure.requestFailed(error) }
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.Webhook.Failure.cancelled }
            catch { throw APIClient.Webhook.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.Webhook.Failure.cancelled }
        catch { throw APIClient.Webhook.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(APIClient.Webhook.Response.self, from: data)
                return APIClient.Webhook.Result(body: body)
            } catch {
                throw APIClient.Webhook.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 400:
            do {
                let payload = try decoder.decode(APIClient.ValidationError.self, from: data)
                throw APIClient.Webhook.Failure.badRequest(payload)
            } catch let error as APIClient.Webhook.Failure {
                throw error
            } catch {
                throw APIClient.Webhook.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.Webhook.Failure.unexpectedStatus(statusCode, data)
        }
    }
}

public struct APIUsersClient: Sendable {
    private let _actor: APIClient

    init(_actor: APIClient) {
        self._actor = _actor
    }

    /// List users with pagination
    public func listUsers(page: Int? = nil, limit: Int? = nil) async throws(APIClient.UsersListUsers.Failure) -> APIClient.UsersListUsers.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        let path = "/users"
        guard var components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersListUsers.Failure.unexpectedStatus(-1, Data())
        }
        var queryItems: [URLQueryItem] = []
        if let value = page {
            for stringValue in Kizuna.stringifyQueryValue(value) {
                queryItems.append(URLQueryItem(name: "page", value: stringValue))
            }
        }
        if let value = limit {
            for stringValue in Kizuna.stringifyQueryValue(value) {
                queryItems.append(URLQueryItem(name: "limit", value: stringValue))
            }
        }
        if !queryItems.isEmpty { components.queryItems = queryItems }
        guard let url = components.url else { throw APIClient.UsersListUsers.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "GET"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersListUsers.Failure.cancelled }
            catch { throw APIClient.UsersListUsers.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersListUsers.Failure.cancelled }
        catch { throw APIClient.UsersListUsers.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(APIClient.UsersListUsers.Response.self, from: data)
                return APIClient.UsersListUsers.Result(body: body)
            } catch {
                throw APIClient.UsersListUsers.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 400:
            do {
                let payload = try decoder.decode(APIClient.ValidationError.self, from: data)
                throw APIClient.UsersListUsers.Failure.badRequest(payload)
            } catch let error as APIClient.UsersListUsers.Failure {
                throw error
            } catch {
                throw APIClient.UsersListUsers.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.UsersListUsers.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Search users — required coerced limit and cursor
    public func searchUsers(q: String, limit: Int, cursor: Int) async throws(APIClient.UsersSearchUsers.Failure) -> APIClient.UsersSearchUsers.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        let path = "/users/search"
        guard var components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersSearchUsers.Failure.unexpectedStatus(-1, Data())
        }
        var queryItems: [URLQueryItem] = []
        for stringValue in Kizuna.stringifyQueryValue(q) {
            queryItems.append(URLQueryItem(name: "q", value: stringValue))
        }
        for stringValue in Kizuna.stringifyQueryValue(limit) {
            queryItems.append(URLQueryItem(name: "limit", value: stringValue))
        }
        for stringValue in Kizuna.stringifyQueryValue(cursor) {
            queryItems.append(URLQueryItem(name: "cursor", value: stringValue))
        }
        if !queryItems.isEmpty { components.queryItems = queryItems }
        guard let url = components.url else { throw APIClient.UsersSearchUsers.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "GET"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersSearchUsers.Failure.cancelled }
            catch { throw APIClient.UsersSearchUsers.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersSearchUsers.Failure.cancelled }
        catch { throw APIClient.UsersSearchUsers.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(APIClient.UsersSearchUsers.Response.self, from: data)
                return APIClient.UsersSearchUsers.Result(body: body)
            } catch {
                throw APIClient.UsersSearchUsers.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 400:
            do {
                let payload = try decoder.decode(APIClient.ValidationError.self, from: data)
                throw APIClient.UsersSearchUsers.Failure.badRequest(payload)
            } catch let error as APIClient.UsersSearchUsers.Failure {
                throw error
            } catch {
                throw APIClient.UsersSearchUsers.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.UsersSearchUsers.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Get a user by id
    public func getUser(id: String, xRequestIdHeader: String) async throws(APIClient.UsersGetUser.Failure) -> APIClient.UsersGetUser.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        var path = "/users/:id"
        path = path.replacingOccurrences(of: ":id", with: Kizuna.encodePathSegment(id))
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersGetUser.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.UsersGetUser.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "GET"
        request.setValue(Kizuna.stringifyQueryValue(xRequestIdHeader).joined(separator: ", "), forHTTPHeaderField: "x-request-id")
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersGetUser.Failure.cancelled }
            catch { throw APIClient.UsersGetUser.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersGetUser.Failure.cancelled }
        catch { throw APIClient.UsersGetUser.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let httpResponse = response as? HTTPURLResponse
        let statusCode = httpResponse?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(API.User.self, from: data)
                let xRequestId = httpResponse?.value(forHTTPHeaderField: "x-request-id")
                return APIClient.UsersGetUser.Result(body: body, headers: .init(xRequestId: xRequestId))
            } catch {
                throw APIClient.UsersGetUser.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 404:
            do {
                let payload = try decoder.decode(API.ProblemDetails.self, from: data)
                throw APIClient.UsersGetUser.Failure.notFound(payload)
            } catch let error as APIClient.UsersGetUser.Failure {
                throw error
            } catch {
                throw APIClient.UsersGetUser.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.UsersGetUser.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Create a user
    public func createUser(name: String, email: String, last_name: String? = nil) async throws(APIClient.UsersCreateUser.Failure) -> APIClient.UsersCreateUser.Result {
        let (baseURL, session, encoder, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        let path = "/users"
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersCreateUser.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.UsersCreateUser.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        let body = API.CreateUserInput(name: name, email: email, last_name: last_name)
        do {
            request.httpBody = try encoder.encode(body)
        } catch { throw APIClient.UsersCreateUser.Failure.requestFailed(error) }
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersCreateUser.Failure.cancelled }
            catch { throw APIClient.UsersCreateUser.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersCreateUser.Failure.cancelled }
        catch { throw APIClient.UsersCreateUser.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 201:
            do {
                let body = try decoder.decode(API.User.self, from: data)
                return APIClient.UsersCreateUser.Result(body: body)
            } catch {
                throw APIClient.UsersCreateUser.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 400:
            do {
                let payload = try decoder.decode(API.ProblemDetails.self, from: data)
                throw APIClient.UsersCreateUser.Failure.badRequest(payload)
            } catch let error as APIClient.UsersCreateUser.Failure {
                throw error
            } catch {}
            do {
                let payload = try decoder.decode(APIClient.ValidationError.self, from: data)
                throw APIClient.UsersCreateUser.Failure.validationError(payload)
            } catch let error as APIClient.UsersCreateUser.Failure {
                throw error
            } catch {}
            throw APIClient.UsersCreateUser.Failure.decoding(DecodingError.dataCorrupted(.init(codingPath: [], debugDescription: "No matching type for status 400")), statusCode: statusCode, data: data)
        default:
            throw APIClient.UsersCreateUser.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Delete a user
    @available(*, deprecated)
    public func deleteUser(id: String) async throws(APIClient.UsersDeleteUser.Failure) -> APIClient.UsersDeleteUser.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        var path = "/users/:id"
        path = path.replacingOccurrences(of: ":id", with: Kizuna.encodePathSegment(id))
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersDeleteUser.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.UsersDeleteUser.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "DELETE"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersDeleteUser.Failure.cancelled }
            catch { throw APIClient.UsersDeleteUser.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersDeleteUser.Failure.cancelled }
        catch { throw APIClient.UsersDeleteUser.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(APIClient.UsersDeleteUser.Response.self, from: data)
                return APIClient.UsersDeleteUser.Result(body: body)
            } catch {
                throw APIClient.UsersDeleteUser.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 404:
            do {
                let payload = try decoder.decode(API.ProblemDetails.self, from: data)
                throw APIClient.UsersDeleteUser.Failure.notFound(payload)
            } catch let error as APIClient.UsersDeleteUser.Failure {
                throw error
            } catch {
                throw APIClient.UsersDeleteUser.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.UsersDeleteUser.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Archive a user — first call returns 201, subsequent calls 200
    public func archiveUser(id: String) async throws(APIClient.UsersArchiveUser.Failure) -> APIClient.UsersArchiveUser.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        var path = "/users/:id/archive"
        path = path.replacingOccurrences(of: ":id", with: Kizuna.encodePathSegment(id))
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersArchiveUser.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.UsersArchiveUser.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "POST"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersArchiveUser.Failure.cancelled }
            catch { throw APIClient.UsersArchiveUser.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersArchiveUser.Failure.cancelled }
        catch { throw APIClient.UsersArchiveUser.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let payload = try decoder.decode(APIClient.UsersArchiveUser.Response.self, from: data)
                return APIClient.UsersArchiveUser.Result(body: .status200(payload))
            } catch {
                throw APIClient.UsersArchiveUser.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 201:
            do {
                let payload = try decoder.decode(APIClient.UsersArchiveUser.Response201.self, from: data)
                return APIClient.UsersArchiveUser.Result(body: .status201(payload))
            } catch {
                throw APIClient.UsersArchiveUser.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.UsersArchiveUser.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Upload an avatar image
    public func uploadAvatar(file: APIClient.MultipartFile, userId: String) async throws(APIClient.UsersUploadAvatar.Failure) -> APIClient.UsersUploadAvatar.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        let path = "/avatar"
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersUploadAvatar.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.UsersUploadAvatar.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "POST"
        var multipart = Kizuna.MultipartBuilder()
        multipart.appendFile(name: "file", file: file)
        multipart.appendField(name: "userId", value: String(describing: userId))
        request.httpBody = multipart.finalize()
        request.setValue(multipart.contentType, forHTTPHeaderField: "Content-Type")
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersUploadAvatar.Failure.cancelled }
            catch { throw APIClient.UsersUploadAvatar.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersUploadAvatar.Failure.cancelled }
        catch { throw APIClient.UsersUploadAvatar.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(APIClient.UsersUploadAvatar.Response.self, from: data)
                return APIClient.UsersUploadAvatar.Result(body: body)
            } catch {
                throw APIClient.UsersUploadAvatar.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 400:
            do {
                let payload = try decoder.decode(APIClient.ValidationError.self, from: data)
                throw APIClient.UsersUploadAvatar.Failure.badRequest(payload)
            } catch let error as APIClient.UsersUploadAvatar.Failure {
                throw error
            } catch {
                throw APIClient.UsersUploadAvatar.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.UsersUploadAvatar.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Ping a user — exercises z.void() body and response
    public func pingUser(id: String) async throws(APIClient.UsersPingUser.Failure) {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        var path = "/users/:id/ping"
        path = path.replacingOccurrences(of: ":id", with: Kizuna.encodePathSegment(id))
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersPingUser.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.UsersPingUser.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "POST"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersPingUser.Failure.cancelled }
            catch { throw APIClient.UsersPingUser.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersPingUser.Failure.cancelled }
        catch { throw APIClient.UsersPingUser.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 204:
            return
        case 400:
            do {
                let payload = try decoder.decode(APIClient.ValidationError.self, from: data)
                throw APIClient.UsersPingUser.Failure.badRequest(payload)
            } catch let error as APIClient.UsersPingUser.Failure {
                throw error
            } catch {
                throw APIClient.UsersPingUser.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.UsersPingUser.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// List work items — exercises a z.void() arm in a multi-status success union and enum values that are not valid Swift identifiers
    public func getMyWork() async throws(APIClient.UsersGetMyWork.Failure) -> APIClient.UsersGetMyWork.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        let path = "/work"
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersGetMyWork.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.UsersGetMyWork.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "GET"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersGetMyWork.Failure.cancelled }
            catch { throw APIClient.UsersGetMyWork.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersGetMyWork.Failure.cancelled }
        catch { throw APIClient.UsersGetMyWork.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let payload = try decoder.decode(APIClient.UsersGetMyWork.Response.self, from: data)
                return APIClient.UsersGetMyWork.Result(body: .status200(payload))
            } catch {
                throw APIClient.UsersGetMyWork.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        case 204:
            return APIClient.UsersGetMyWork.Result(body: .status204)
        default:
            throw APIClient.UsersGetMyWork.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Check user existence — exercises HEAD body stripping
    public func checkUser(id: String) async throws(APIClient.UsersCheckUser.Failure) {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        var path = "/users/:id/check"
        path = path.replacingOccurrences(of: ":id", with: Kizuna.encodePathSegment(id))
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersCheckUser.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.UsersCheckUser.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "HEAD"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersCheckUser.Failure.cancelled }
            catch { throw APIClient.UsersCheckUser.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersCheckUser.Failure.cancelled }
        catch { throw APIClient.UsersCheckUser.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            return
        case 404:
            do {
                let payload = try decoder.decode(API.ProblemDetails.self, from: data)
                throw APIClient.UsersCheckUser.Failure.notFound(payload)
            } catch let error as APIClient.UsersCheckUser.Failure {
                throw error
            } catch {
                throw APIClient.UsersCheckUser.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.UsersCheckUser.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Describe allowed operations — exercises OPTIONS routing
    public func describeUsers() async throws(APIClient.UsersDescribeUsers.Failure) -> APIClient.UsersDescribeUsers.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        let path = "/users/describe"
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.UsersDescribeUsers.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.UsersDescribeUsers.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "OPTIONS"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.UsersDescribeUsers.Failure.cancelled }
            catch { throw APIClient.UsersDescribeUsers.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.UsersDescribeUsers.Failure.cancelled }
        catch { throw APIClient.UsersDescribeUsers.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(APIClient.UsersDescribeUsers.Response.self, from: data)
                return APIClient.UsersDescribeUsers.Result(body: body)
            } catch {
                throw APIClient.UsersDescribeUsers.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.UsersDescribeUsers.Failure.unexpectedStatus(statusCode, data)
        }
    }
}

public struct APIHealthClient: Sendable {
    private let _actor: APIClient

    init(_actor: APIClient) {
        self._actor = _actor
    }

    /// Health check — exercises nested sub-client routing
    public func check() async throws(APIClient.HealthCheck.Failure) -> APIClient.HealthCheck.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        let path = "/health"
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.HealthCheck.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.HealthCheck.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "GET"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.HealthCheck.Failure.cancelled }
            catch { throw APIClient.HealthCheck.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.HealthCheck.Failure.cancelled }
        catch { throw APIClient.HealthCheck.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(APIClient.HealthCheck.Response.self, from: data)
                return APIClient.HealthCheck.Result(body: body)
            } catch {
                throw APIClient.HealthCheck.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.HealthCheck.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Version — exercises second method in a sub-client group
    public func version() async throws(APIClient.HealthVersion.Failure) -> APIClient.HealthVersion.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        let path = "/health/version"
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.HealthVersion.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.HealthVersion.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "GET"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.HealthVersion.Failure.cancelled }
            catch { throw APIClient.HealthVersion.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.HealthVersion.Failure.cancelled }
        catch { throw APIClient.HealthVersion.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode(APIClient.HealthVersion.Response.self, from: data)
                return APIClient.HealthVersion.Result(body: body)
            } catch {
                throw APIClient.HealthVersion.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.HealthVersion.Failure.unexpectedStatus(statusCode, data)
        }
    }

    /// Health history — exercises array return type qualification
    public func history() async throws(APIClient.HealthHistory.Failure) -> APIClient.HealthHistory.Result {
        let (baseURL, session, _, decoder, requestMiddleware, responseMiddleware) = await _actor._kizunaContext()
        let timeout = _actor.timeout
        let path = "/health/history"
        guard let components = URLComponents(url: Kizuna.appendPath(baseURL, path), resolvingAgainstBaseURL: false) else {
            throw APIClient.HealthHistory.Failure.unexpectedStatus(-1, Data())
        }
        guard let url = components.url else { throw APIClient.HealthHistory.Failure.unexpectedStatus(-1, Data()) }
        var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: timeout)
        request.httpMethod = "GET"
        if let middleware = requestMiddleware {
            do { try await middleware(&request) }
            catch is CancellationError { throw APIClient.HealthHistory.Failure.cancelled }
            catch { throw APIClient.HealthHistory.Failure.requestFailed(error) }
        }
        let data: Foundation.Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch is CancellationError { throw APIClient.HealthHistory.Failure.cancelled }
        catch { throw APIClient.HealthHistory.Failure.requestFailed(error) }
        if let middleware = responseMiddleware {
            await middleware(request, data, response)
        }
        let statusCode = (response as? HTTPURLResponse)?.statusCode ?? -1
        switch statusCode {
        case 200:
            do {
                let body = try decoder.decode([APIClient.HealthHistory.ResponseItem].self, from: data)
                return APIClient.HealthHistory.Result(body: body)
            } catch {
                throw APIClient.HealthHistory.Failure.decoding(error, statusCode: statusCode, data: data)
            }
        default:
            throw APIClient.HealthHistory.Failure.unexpectedStatus(statusCode, data)
        }
    }
}

private enum Kizuna {
    nonisolated(unsafe) static let iso8601Formatter: ISO8601DateFormatter = {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        return formatter
    }()

    nonisolated(unsafe) static let iso8601FractionalFormatter: ISO8601DateFormatter = {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return formatter
    }()

    @Sendable static func decodeDate(_ decoder: Decoder) throws -> Date {
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        if let date = iso8601FractionalFormatter.date(from: raw) { return date }
        if let date = iso8601Formatter.date(from: raw) { return date }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "Invalid ISO8601 date: \(raw)")
    }

    static func makeJSONEncoder() -> JSONEncoder {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .custom { date, encoder in
            var container = encoder.singleValueContainer()
            try container.encode(iso8601FractionalFormatter.string(from: date))
        }
        return encoder
    }

    static func makeJSONDecoder() -> JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .custom(decodeDate)
        return decoder
    }

    private static let pathSegmentAllowed: CharacterSet = {
        var allowed = CharacterSet.urlPathAllowed
        allowed.remove(charactersIn: "/")
        return allowed
    }()

    static func encodePathSegment(_ value: String) -> String {
        value.addingPercentEncoding(withAllowedCharacters: pathSegmentAllowed) ?? value
    }

    static func appendPath(_ base: URL, _ path: String) -> URL {
        base.appending(path: path, directoryHint: .notDirectory)
    }

    static func stringifyQueryValue(_ value: Any) -> [String] {
        switch value {
        case let date as Date:
            return [iso8601Formatter.string(from: date)]
        case let array as [Any]:
            return array.flatMap { stringifyQueryValue($0) }
        case let raw as any RawRepresentable where raw.rawValue is CustomStringConvertible:
            return [String(describing: raw.rawValue)]
        case let convertible as CustomStringConvertible:
            return [convertible.description]
        default:
            return [String(describing: value)]
        }
    }

    struct MultipartBuilder {
        let boundary: String
        private var data = Foundation.Data()

        init(boundary: String = "kizuna-\(UUID().uuidString)") {
            self.boundary = boundary
        }

        mutating func appendField(name: String, value: String) {
            data.append("--\(boundary)\r\n".data(using: .utf8)!)
            data.append("Content-Disposition: form-data; name=\"\(name)\"\r\n\r\n".data(using: .utf8)!)
            data.append(value.data(using: .utf8)!)
            data.append("\r\n".data(using: .utf8)!)
        }

        mutating func appendFile(name: String, file: APIClient.MultipartFile) {
            data.append("--\(boundary)\r\n".data(using: .utf8)!)
            data.append("Content-Disposition: form-data; name=\"\(name)\"; filename=\"\(file.filename)\"\r\n".data(using: .utf8)!)
            data.append("Content-Type: \(file.mimeType)\r\n\r\n".data(using: .utf8)!)
            data.append(file.data)
            data.append("\r\n".data(using: .utf8)!)
        }

        func finalize() -> Foundation.Data {
            var result = data
            result.append("--\(boundary)--\r\n".data(using: .utf8)!)
            return result
        }

        var contentType: String {
            "multipart/form-data; boundary=\(boundary)"
        }
    }
}
