// Generated by @ts-kizuna/kotlin. Do not edit by hand.

@file:Suppress("PropertyName", "ConstructorParameterNaming")

package com.kizuna.demo

import kotlinx.serialization.*
import kotlinx.serialization.json.*
import kotlinx.datetime.Instant
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import okhttp3.HttpUrl.Companion.toHttpUrl

interface KizunaQueryValue {
    val wireValue: String
}

object API {

    /** A user in the system */
    @Serializable
    data class User(
        val id: String,
        val name: String,
        @Deprecated("use `email_address` instead.") val email: String,
        val email_address: String? = null,
        val last_name: String? = null,
        val avatar: Avatar? = null,
        val avatars: List<AvatarsItem>? = null
    ) {

        @Serializable
        data class Avatar(
            val id: String,
            val url: String
        )

        @Serializable
        data class AvatarsItem(
            val id: String,
            val url: String
        )
    }

    /** RFC 9457 Problem Details error response. */
    @Serializable
    data class ProblemDetails(
        val type: String,
        val title: String,
        val status: Int,
        val detail: String
    )

    @Serializable
    data class CreateUserInput(
        val name: String,
        val email: String,
        val last_name: String? = null,
        val phone: String? = null
    )

    @OptIn(ExperimentalSerializationApi::class)
    @JsonClassDiscriminator("channel")
    @Serializable
    sealed interface NotificationEvent

    @SerialName("email")
    @Serializable
    data class EmailEvent(
        val to: String,
        val subject: String
    ) : NotificationEvent

    @SerialName("sms")
    @Serializable
    data class SmsEvent(
        val phone: String,
        val text: String
    ) : NotificationEvent

    @Serializable
    data class EventRecord(
        val id: String,
        val kind: Kind,
        val occurredAt: Instant,
        val userId: String
    ) {

        @Serializable
        enum class Kind(override val wireValue: String) : KizunaQueryValue {
            @SerialName("login") LOGIN("login"),
            @SerialName("logout") LOGOUT("logout"),
            @SerialName("signup") SIGNUP("signup")
        }
    }
}

class APIClient(private val baseUrl: String, requestContext: RequestContext = RequestContext(), private val client: OkHttpClient = OkHttpClient(), private val json: Json = Json { ignoreUnknownKeys = true }, private val requestInterceptor: (suspend (Request.Builder) -> Unit)? = null, private val responseInterceptor: (suspend (Request, Response) -> Unit)? = null) {

    /** Values sent as headers on every request, from the contract's request context. */
    data class RequestContext(
        val xPosthogSessionId: String? = null,
        val xPosthogDistinctId: String? = null
    )

    private val requestContextHeaders: Map<String, String> = buildMap {
        if (requestContext.xPosthogSessionId != null) put("x-posthog-session-id", requestContext.xPosthogSessionId!!)
        if (requestContext.xPosthogDistinctId != null) put("x-posthog-distinct-id", requestContext.xPosthogDistinctId!!)
    }

    data class MultipartFile(
        val data: ByteArray,
        val filename: String,
        val mimeType: String = "application/octet-stream"
    )

    @Serializable
    data class ValidationError(
        val type: String,
        val title: String,
        val status: Int,
        val detail: String,
        val errors: List<ValidationIssue>
    )

    @Serializable
    data class ValidationIssue(
        val code: String,
        val path: List<String>,
        val message: String
    )

    object UsersListUsers {

        @Serializable
        data class ResponseBody(
            val users: List<API.User>,
            val total: Double
        )

        data class Query(
            val page: Int? = null,
            val limit: Int? = null
        )

        sealed interface Args {
            val query: Query?
        }

        object Scope {
            fun query(page: Int? = null, limit: Int? = null): AfterQuery = AfterQuery(query = Query(page = page, limit = limit))
        }

        class AfterQuery internal constructor(override val query: Query?) : Args

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class BadRequest(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersExportUsers {

        data class Response(val body: String)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersUserBadge {

        data class Params(val id: String)

        sealed interface Args {
            val params: Params
        }

        object Scope {
            fun params(id: String): AfterParams = AfterParams(params = Params(id = id))
        }

        class AfterParams internal constructor(override val params: Params) : Args

        data class Response(val body: JsonElement)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class NotFound(val body: API.ProblemDetails) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersSearchUsers {

        @Serializable
        data class ResponseBody(
            val users: List<API.User>,
            val nextCursor: Double? = null
        )

        data class Query(
            val q: String,
            val limit: Int,
            val cursor: Int
        )

        sealed interface Args {
            val query: Query
        }

        object Scope {
            fun query(q: String, limit: Int, cursor: Int): AfterQuery = AfterQuery(query = Query(q = q, limit = limit, cursor = cursor))
        }

        class AfterQuery internal constructor(override val query: Query) : Args

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class BadRequest(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersGetUser {

        data class Params(val id: String)

        data class Headers(val xRequestId: String)

        sealed interface Args {
            val params: Params
            val headers: Headers
        }

        object Scope {
            fun params(id: String): AfterParams = AfterParams(params = Params(id = id))
        }

        class AfterParams internal constructor(internal val params: Params) {
            fun headers(xRequestId: String): AfterHeaders = AfterHeaders(params = params, headers = Headers(xRequestId = xRequestId))
        }

        class AfterHeaders internal constructor(override val params: Params, override val headers: Headers) : Args

        data class Response(
            val body: API.User,
            val headers: Headers
        ) {

            data class Headers(val xRequestId: String?)
        }

        sealed class Failure(message: String? = null) : Exception(message) {
            data class NotFound(val body: API.ProblemDetails) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersCreateUser {

        data class Body(
            val name: String,
            val email: String,
            val last_name: String? = null,
            val phone: String? = null
        )

        sealed interface Args {
            val body: Body
        }

        object Scope {
            fun body(name: String, email: String, last_name: String? = null, phone: String? = null): AfterBody = AfterBody(body = Body(name = name, email = email, last_name = last_name, phone = phone))
        }

        class AfterBody internal constructor(override val body: Body) : Args

        data class Response(val body: API.User)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class BadRequest(val body: API.ProblemDetails) : Failure()
            data class ValidationError(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersDeleteUser {

        @Serializable
        data class ResponseBody(val success: Boolean)

        data class Params(val id: String)

        sealed interface Args {
            val params: Params
        }

        object Scope {
            fun params(id: String): AfterParams = AfterParams(params = Params(id = id))
        }

        class AfterParams internal constructor(override val params: Params) : Args

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class NotFound(val body: API.ProblemDetails) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersArchiveUser {

        @Serializable
        data class ResponseBody(
            val alreadyArchived: Boolean,
            val userId: String
        )

        @Serializable
        data class Response201(
            val archivedAt: Instant,
            val userId: String
        )

        data class Params(val id: String)

        sealed interface Args {
            val params: Params
        }

        object Scope {
            fun params(id: String): AfterParams = AfterParams(params = Params(id = id))
        }

        class AfterParams internal constructor(override val params: Params) : Args

        sealed interface Success {
            data class Status200(val body: ResponseBody) : Success
            data class Status201(val body: Response201) : Success
        }

        data class Response(val body: Success)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersUploadAvatar {

        data class Input(
            val file: APIClient.MultipartFile,
            val userId: String
        )

        @Serializable
        data class ResponseBody(
            val size: Double,
            val userId: String
        )

        data class Body(
            val file: APIClient.MultipartFile,
            val userId: String
        )

        sealed interface Args {
            val body: Body
        }

        object Scope {
            fun body(file: APIClient.MultipartFile, userId: String): AfterBody = AfterBody(body = Body(file = file, userId = userId))
        }

        class AfterBody internal constructor(override val body: Body) : Args

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class BadRequest(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersPingUser {

        data class Params(val id: String)

        sealed interface Args {
            val params: Params
        }

        object Scope {
            fun params(id: String): AfterParams = AfterParams(params = Params(id = id))
        }

        class AfterParams internal constructor(override val params: Params) : Args

        sealed class Failure(message: String? = null) : Exception(message) {
            data class BadRequest(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersGetMyWork {

        @Serializable
        data class ResponseBody(
            val items: List<String>,
            val contentType: ResponseBodyContentType
        )

        @Serializable
        enum class ResponseBodyContentType(override val wireValue: String) : KizunaQueryValue {
            @SerialName("image/jpeg") IMAGE_JPEG("image/jpeg"),
            @SerialName("text-plain") TEXT_PLAIN("text-plain"),
            @SerialName("video.mp4") VIDEO_MP4("video.mp4"),
            @SerialName("3d-model") _3D_MODEL("3d-model")
        }

        sealed interface Success {
            data class Status200(val body: ResponseBody) : Success
            data class Status204(val body: Unit) : Success
        }

        data class Response(val body: Success)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersCheckUser {

        @Serializable
        data class ResponseBody(val exists: Boolean)

        data class Params(val id: String)

        sealed interface Args {
            val params: Params
        }

        object Scope {
            fun params(id: String): AfterParams = AfterParams(params = Params(id = id))
        }

        class AfterParams internal constructor(override val params: Params) : Args

        sealed class Failure(message: String? = null) : Exception(message) {
            data class NotFound(val body: API.ProblemDetails) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object UsersDescribeUsers {

        @Serializable
        data class ResponseBody(val allow: String)

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object HealthCheck {

        @Serializable
        data class ResponseBody(val ok: Boolean)

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object HealthVersion {

        @Serializable
        data class ResponseBody(val version: String)

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object HealthHistory {

        @Serializable
        data class ResponseBodyItem(
            val ok: Boolean,
            val checkedAt: Instant
        )

        data class Response(val body: List<ResponseBodyItem>)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object NotificationsSendNotification {

        @Serializable
        data class Response202(val accepted: Boolean)

        data class Body(val payload: API.NotificationEvent)

        sealed interface Args {
            val body: Body
        }

        object Scope {
            fun body(payload: API.NotificationEvent): AfterBody = AfterBody(body = Body(payload = payload))
        }

        class AfterBody internal constructor(override val body: Body) : Args

        data class Response(val body: Response202)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class BadRequest(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object NotificationsListEvents {

        @Serializable
        enum class QueryKind(override val wireValue: String) : KizunaQueryValue {
            @SerialName("login") LOGIN("login"),
            @SerialName("logout") LOGOUT("logout"),
            @SerialName("signup") SIGNUP("signup")
        }

        @Serializable
        data class ResponseBody(
            val events: List<API.EventRecord>,
            val echo: ResponseBodyEcho
        )

        @Serializable
        data class ResponseBodyEcho(
            val since: Instant? = null,
            val kind: ResponseBodyEchoKind? = null,
            val ids: List<String>? = null,
            val label: String? = null,
            val tagIds: List<String>? = null,
            val sessionId: String? = null
        )

        @Serializable
        enum class ResponseBodyEchoKind(override val wireValue: String) : KizunaQueryValue {
            @SerialName("login") LOGIN("login"),
            @SerialName("logout") LOGOUT("logout"),
            @SerialName("signup") SIGNUP("signup")
        }

        data class Query(
            val since: Instant? = null,
            val kind: QueryKind? = null,
            val ids: List<String>? = null,
            val label: String? = null,
            val tagIds: List<String>? = null
        )

        sealed interface Args {
            val query: Query?
        }

        object Scope {
            fun query(since: Instant? = null, kind: QueryKind? = null, ids: List<String>? = null, label: String? = null, tagIds: List<String>? = null): AfterQuery = AfterQuery(query = Query(since = since, kind = kind, ids = ids, label = label, tagIds = tagIds))
        }

        class AfterQuery internal constructor(override val query: Query?) : Args

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class BadRequest(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object NotificationsValidateConfig {

        @Serializable
        data class Input(
            val default: String,
            val interval: Int
        )

        /** Validation result */
        @Serializable
        data class ResponseBody(val status: String)

        data class Body(
            val default: String,
            val interval: Int
        )

        sealed interface Args {
            val body: Body
        }

        object Scope {
            fun body(default: String, interval: Int): AfterBody = AfterBody(body = Body(default = default, interval = interval))
        }

        class AfterBody internal constructor(override val body: Body) : Args

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class BadRequest(val body: API.ProblemDetails) : Failure()
            data object Unauthorized : Failure()
            data class ValidationError(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object NotificationsWebhook {

        @Serializable
        data class ResponseBody(val received: Boolean)

        data class Body(val payload: JsonElement)

        sealed interface Args {
            val body: Body
        }

        object Scope {
            fun body(payload: JsonElement): AfterBody = AfterBody(body = Body(payload = payload))
        }

        class AfterBody internal constructor(override val body: Body) : Args

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class BadRequest(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object MembersListMembers {

        @Serializable
        data class ResponseBody(val members: List<API.User>)

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object MembersInviteMember {

        @Serializable
        data class Input(val email: String)

        data class Body(val email: String)

        sealed interface Args {
            val body: Body
        }

        object Scope {
            fun body(email: String): AfterBody = AfterBody(body = Body(email = email))
        }

        class AfterBody internal constructor(override val body: Body) : Args

        data class Response(val body: API.User)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Conflict(val body: API.ProblemDetails) : Failure()
            data class BadRequest(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object WorkspaceGetWorkspace {

        @Serializable
        data class ResponseBody(
            val id: String,
            val name: String
        )

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object WorkspaceDeleteWorkspace {

        @Serializable
        data class ResponseBody(val ok: Boolean)

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object WorkspaceTransfer {

        @Serializable
        data class Input(val toUserId: String)

        @Serializable
        data class ResponseBody(val ok: Boolean)

        data class Body(val toUserId: String)

        sealed interface Args {
            val body: Body
        }

        object Scope {
            fun body(toUserId: String): AfterBody = AfterBody(body = Body(toUserId = toUserId))
        }

        class AfterBody internal constructor(override val body: Body) : Args

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class BadRequest(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object InvitesGetInvite {

        @Serializable
        data class ResponseBody(
            val inviteId: String,
            val email: String
        )

        data class Params(val token: String)

        sealed interface Args {
            val params: Params
        }

        object Scope {
            fun params(token: String): AfterParams = AfterParams(params = Params(token = token))
        }

        class AfterParams internal constructor(override val params: Params) : Args

        data class Response(val body: ResponseBody)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class NotFound(val body: API.ProblemDetails) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    object InvitesAcceptInvite {

        @Serializable
        data class Input(val name: String)

        @Serializable
        data class Response201(val userId: String)

        data class Params(val token: String)

        data class Body(val name: String)

        sealed interface Args {
            val params: Params
            val body: Body
        }

        object Scope {
            fun params(token: String): AfterParams = AfterParams(params = Params(token = token))
        }

        class AfterParams internal constructor(internal val params: Params) {
            fun body(name: String): AfterBody = AfterBody(params = params, body = Body(name = name))
        }

        class AfterBody internal constructor(override val params: Params, override val body: Body) : Args

        data class Response(val body: Response201)

        sealed class Failure(message: String? = null) : Exception(message) {
            data class NotFound(val body: API.ProblemDetails) : Failure()
            data class BadRequest(val body: APIClient.ValidationError) : Failure()
            data class Unexpected(val statusCode: Int, val data: ByteArray) : Failure("Unexpected status $statusCode")
            data class Decoding(override val cause: Throwable, val statusCode: Int, val data: ByteArray) : Failure(cause.message)
        }
    }

    val users = APIUsersClient(client, baseUrl, json, requestContextHeaders, requestInterceptor, responseInterceptor)

    val health = APIHealthClient(client, baseUrl, json, requestContextHeaders, requestInterceptor, responseInterceptor)

    val notifications = APINotificationsClient(client, baseUrl, json, requestContextHeaders, requestInterceptor, responseInterceptor)

    val members = APIMembersClient(client, baseUrl, json, requestContextHeaders, requestInterceptor, responseInterceptor)

    val workspace = APIWorkspaceClient(client, baseUrl, json, requestContextHeaders, requestInterceptor, responseInterceptor)

    val invites = APIInvitesClient(client, baseUrl, json, requestContextHeaders, requestInterceptor, responseInterceptor)
}

class APIUsersClient(private val client: OkHttpClient, private val baseUrl: String, private val json: Json, private val requestContextHeaders: Map<String, String>, private val requestInterceptor: (suspend (Request.Builder) -> Unit)?, private val responseInterceptor: (suspend (Request, Response) -> Unit)?) {

    /** List users with pagination */
    @Throws(APIClient.UsersListUsers.Failure::class)
    suspend fun listUsers(build: APIClient.UsersListUsers.Scope.() -> APIClient.UsersListUsers.Args = { query() }): APIClient.UsersListUsers.Response {
        val args = APIClient.UsersListUsers.Scope.build()
        val query = args.query ?: APIClient.UsersListUsers.Query()
        var path = "/users"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        if (query.page != null) {
            for (stringValue in Kizuna.stringifyQueryValue(query.page)) {
                urlBuilder.addQueryParameter("page", stringValue)
            }
        }
        if (query.limit != null) {
            for (stringValue in Kizuna.stringifyQueryValue(query.limit)) {
                urlBuilder.addQueryParameter("limit", stringValue)
            }
        }
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.UsersListUsers.ResponseBody>(data.decodeToString())
                        return@use APIClient.UsersListUsers.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.UsersListUsers.Failure.Decoding(error, statusCode, data) }
                }
                400 -> {
                    val payload = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.UsersListUsers.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.UsersListUsers.Failure.BadRequest(body = payload)
                }
                else -> throw APIClient.UsersListUsers.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Export users as CSV — exercises a non-JSON (text/csv) raw response body */
    @Throws(APIClient.UsersExportUsers.Failure::class)
    suspend fun exportUsers(): APIClient.UsersExportUsers.Response {
        var path = "/users/export"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<String>(data.decodeToString())
                        return@use APIClient.UsersExportUsers.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.UsersExportUsers.Failure.Decoding(error, statusCode, data) }
                }
                else -> throw APIClient.UsersExportUsers.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Download a user badge — exercises a binary (BinarySchema) response body */
    @Throws(APIClient.UsersUserBadge.Failure::class)
    suspend fun userBadge(build: APIClient.UsersUserBadge.Scope.() -> APIClient.UsersUserBadge.Args): APIClient.UsersUserBadge.Response {
        val args = APIClient.UsersUserBadge.Scope.build()
        val params = args.params
        var path = "/users/:id/badge"
        path = path.replace(":id", Kizuna.encodePathSegment(params.id))
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<JsonElement>(data.decodeToString())
                        return@use APIClient.UsersUserBadge.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.UsersUserBadge.Failure.Decoding(error, statusCode, data) }
                }
                404 -> {
                    val payload = try {
                        json.decodeFromString<API.ProblemDetails>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.UsersUserBadge.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.UsersUserBadge.Failure.NotFound(body = payload)
                }
                else -> throw APIClient.UsersUserBadge.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Search users — required coerced limit and cursor */
    @Throws(APIClient.UsersSearchUsers.Failure::class)
    suspend fun searchUsers(build: APIClient.UsersSearchUsers.Scope.() -> APIClient.UsersSearchUsers.Args): APIClient.UsersSearchUsers.Response {
        val args = APIClient.UsersSearchUsers.Scope.build()
        val query = args.query
        var path = "/users/search"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        for (stringValue in Kizuna.stringifyQueryValue(query.q)) {
            urlBuilder.addQueryParameter("q", stringValue)
        }
        for (stringValue in Kizuna.stringifyQueryValue(query.limit)) {
            urlBuilder.addQueryParameter("limit", stringValue)
        }
        for (stringValue in Kizuna.stringifyQueryValue(query.cursor)) {
            urlBuilder.addQueryParameter("cursor", stringValue)
        }
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.UsersSearchUsers.ResponseBody>(data.decodeToString())
                        return@use APIClient.UsersSearchUsers.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.UsersSearchUsers.Failure.Decoding(error, statusCode, data) }
                }
                400 -> {
                    val payload = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.UsersSearchUsers.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.UsersSearchUsers.Failure.BadRequest(body = payload)
                }
                else -> throw APIClient.UsersSearchUsers.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Get a user by id */
    @Throws(APIClient.UsersGetUser.Failure::class)
    suspend fun getUser(build: APIClient.UsersGetUser.Scope.() -> APIClient.UsersGetUser.Args): APIClient.UsersGetUser.Response {
        val args = APIClient.UsersGetUser.Scope.build()
        val params = args.params
        val headers = args.headers
        var path = "/users/:id"
        path = path.replace(":id", Kizuna.encodePathSegment(params.id))
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestBuilder = requestBuilder.header("x-request-id", Kizuna.stringifyQueryValue(headers.xRequestId).joinToString(", "))
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<API.User>(data.decodeToString())
                        val xRequestId = httpResponse.header("x-request-id")
                        return@use APIClient.UsersGetUser.Response(body = payload, headers = APIClient.UsersGetUser.Response.Headers(xRequestId = xRequestId))
                    }
                    catch (error: Exception) { throw APIClient.UsersGetUser.Failure.Decoding(error, statusCode, data) }
                }
                404 -> {
                    val payload = try {
                        json.decodeFromString<API.ProblemDetails>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.UsersGetUser.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.UsersGetUser.Failure.NotFound(body = payload)
                }
                else -> throw APIClient.UsersGetUser.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Create a user */
    @Throws(APIClient.UsersCreateUser.Failure::class)
    suspend fun createUser(build: APIClient.UsersCreateUser.Scope.() -> APIClient.UsersCreateUser.Args): APIClient.UsersCreateUser.Response {
        val args = APIClient.UsersCreateUser.Scope.build()
        val body = args.body
        var path = "/users"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBody: RequestBody? = null
        val payload = API.CreateUserInput(name = body.name, email = body.email, last_name = body.last_name, phone = body.phone)
        requestBody = json.encodeToString(payload).toRequestBody("application/json".toMediaType())
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("POST", requestBody)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                201 -> {
                    try {
                        val payload = json.decodeFromString<API.User>(data.decodeToString())
                        return@use APIClient.UsersCreateUser.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.UsersCreateUser.Failure.Decoding(error, statusCode, data) }
                }
                400 -> {
                    val badRequest = try {
                        json.decodeFromString<API.ProblemDetails>(data.decodeToString())
                    } catch (_: Exception) { null }
                    if (badRequest != null) throw APIClient.UsersCreateUser.Failure.BadRequest(body = badRequest)
                    val validationError = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (_: Exception) { null }
                    if (validationError != null) throw APIClient.UsersCreateUser.Failure.ValidationError(body = validationError)
                    throw APIClient.UsersCreateUser.Failure.Unexpected(statusCode = statusCode, data = data)
                }
                else -> throw APIClient.UsersCreateUser.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Delete a user */
    @Deprecated("Deprecated")
    @Throws(APIClient.UsersDeleteUser.Failure::class)
    suspend fun deleteUser(build: APIClient.UsersDeleteUser.Scope.() -> APIClient.UsersDeleteUser.Args): APIClient.UsersDeleteUser.Response {
        val args = APIClient.UsersDeleteUser.Scope.build()
        val params = args.params
        var path = "/users/:id"
        path = path.replace(":id", Kizuna.encodePathSegment(params.id))
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("DELETE", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.UsersDeleteUser.ResponseBody>(data.decodeToString())
                        return@use APIClient.UsersDeleteUser.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.UsersDeleteUser.Failure.Decoding(error, statusCode, data) }
                }
                404 -> {
                    val payload = try {
                        json.decodeFromString<API.ProblemDetails>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.UsersDeleteUser.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.UsersDeleteUser.Failure.NotFound(body = payload)
                }
                else -> throw APIClient.UsersDeleteUser.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Archive a user — first call returns 201, subsequent calls 200 */
    @Throws(APIClient.UsersArchiveUser.Failure::class)
    suspend fun archiveUser(build: APIClient.UsersArchiveUser.Scope.() -> APIClient.UsersArchiveUser.Args): APIClient.UsersArchiveUser.Response {
        val args = APIClient.UsersArchiveUser.Scope.build()
        val params = args.params
        var path = "/users/:id/archive"
        path = path.replace(":id", Kizuna.encodePathSegment(params.id))
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("POST", ByteArray(0).toRequestBody(null))
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.UsersArchiveUser.ResponseBody>(data.decodeToString())
                        return@use APIClient.UsersArchiveUser.Response(body = APIClient.UsersArchiveUser.Success.Status200(payload))
                    }
                    catch (error: Exception) { throw APIClient.UsersArchiveUser.Failure.Decoding(error, statusCode, data) }
                }
                201 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.UsersArchiveUser.Response201>(data.decodeToString())
                        return@use APIClient.UsersArchiveUser.Response(body = APIClient.UsersArchiveUser.Success.Status201(payload))
                    }
                    catch (error: Exception) { throw APIClient.UsersArchiveUser.Failure.Decoding(error, statusCode, data) }
                }
                else -> throw APIClient.UsersArchiveUser.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Upload an avatar image */
    @Throws(APIClient.UsersUploadAvatar.Failure::class)
    suspend fun uploadAvatar(build: APIClient.UsersUploadAvatar.Scope.() -> APIClient.UsersUploadAvatar.Args): APIClient.UsersUploadAvatar.Response {
        val args = APIClient.UsersUploadAvatar.Scope.build()
        val body = args.body
        var path = "/avatar"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBody: RequestBody? = null
        val multipartBuilder = MultipartBody.Builder().setType(MultipartBody.FORM)
        multipartBuilder.addFormDataPart("file", body.file.filename, body.file.data.toRequestBody(body.file.mimeType.toMediaType()))
        multipartBuilder.addFormDataPart("userId", body.userId.toString())
        requestBody = multipartBuilder.build()
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("POST", requestBody)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.UsersUploadAvatar.ResponseBody>(data.decodeToString())
                        return@use APIClient.UsersUploadAvatar.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.UsersUploadAvatar.Failure.Decoding(error, statusCode, data) }
                }
                400 -> {
                    val payload = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.UsersUploadAvatar.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.UsersUploadAvatar.Failure.BadRequest(body = payload)
                }
                else -> throw APIClient.UsersUploadAvatar.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Ping a user — exercises z.void() body and response */
    @Throws(APIClient.UsersPingUser.Failure::class)
    suspend fun pingUser(build: APIClient.UsersPingUser.Scope.() -> APIClient.UsersPingUser.Args) {
        val args = APIClient.UsersPingUser.Scope.build()
        val params = args.params
        var path = "/users/:id/ping"
        path = path.replace(":id", Kizuna.encodePathSegment(params.id))
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("POST", ByteArray(0).toRequestBody(null))
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                204 -> {
                    Unit
                }
                400 -> {
                    val payload = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.UsersPingUser.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.UsersPingUser.Failure.BadRequest(body = payload)
                }
                else -> throw APIClient.UsersPingUser.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** List work items — exercises a z.void() arm in a multi-status success union and enum values that are not valid Swift identifiers */
    @Throws(APIClient.UsersGetMyWork.Failure::class)
    suspend fun getMyWork(): APIClient.UsersGetMyWork.Response {
        var path = "/work"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.UsersGetMyWork.ResponseBody>(data.decodeToString())
                        return@use APIClient.UsersGetMyWork.Response(body = APIClient.UsersGetMyWork.Success.Status200(payload))
                    }
                    catch (error: Exception) { throw APIClient.UsersGetMyWork.Failure.Decoding(error, statusCode, data) }
                }
                204 -> {
                    try {
                        val payload = json.decodeFromString<Unit>(data.decodeToString())
                        return@use APIClient.UsersGetMyWork.Response(body = APIClient.UsersGetMyWork.Success.Status204(payload))
                    }
                    catch (error: Exception) { throw APIClient.UsersGetMyWork.Failure.Decoding(error, statusCode, data) }
                }
                else -> throw APIClient.UsersGetMyWork.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Check user existence — exercises HEAD body stripping */
    @Throws(APIClient.UsersCheckUser.Failure::class)
    suspend fun checkUser(build: APIClient.UsersCheckUser.Scope.() -> APIClient.UsersCheckUser.Args) {
        val args = APIClient.UsersCheckUser.Scope.build()
        val params = args.params
        var path = "/users/:id/check"
        path = path.replace(":id", Kizuna.encodePathSegment(params.id))
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("HEAD", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    Unit
                }
                404 -> {
                    val payload = try {
                        json.decodeFromString<API.ProblemDetails>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.UsersCheckUser.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.UsersCheckUser.Failure.NotFound(body = payload)
                }
                else -> throw APIClient.UsersCheckUser.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Describe allowed operations — exercises OPTIONS routing */
    @Throws(APIClient.UsersDescribeUsers.Failure::class)
    suspend fun describeUsers(): APIClient.UsersDescribeUsers.Response {
        var path = "/users/describe"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("OPTIONS", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.UsersDescribeUsers.ResponseBody>(data.decodeToString())
                        return@use APIClient.UsersDescribeUsers.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.UsersDescribeUsers.Failure.Decoding(error, statusCode, data) }
                }
                else -> throw APIClient.UsersDescribeUsers.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }
}

class APIHealthClient(private val client: OkHttpClient, private val baseUrl: String, private val json: Json, private val requestContextHeaders: Map<String, String>, private val requestInterceptor: (suspend (Request.Builder) -> Unit)?, private val responseInterceptor: (suspend (Request, Response) -> Unit)?) {

    /** Health check — exercises nested sub-client routing */
    @Throws(APIClient.HealthCheck.Failure::class)
    suspend fun check(): APIClient.HealthCheck.Response {
        var path = "/health"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.HealthCheck.ResponseBody>(data.decodeToString())
                        return@use APIClient.HealthCheck.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.HealthCheck.Failure.Decoding(error, statusCode, data) }
                }
                else -> throw APIClient.HealthCheck.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Version — exercises second method in a sub-client group */
    @Throws(APIClient.HealthVersion.Failure::class)
    suspend fun version(): APIClient.HealthVersion.Response {
        var path = "/health/version"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.HealthVersion.ResponseBody>(data.decodeToString())
                        return@use APIClient.HealthVersion.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.HealthVersion.Failure.Decoding(error, statusCode, data) }
                }
                else -> throw APIClient.HealthVersion.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Health history — exercises array return type qualification */
    @Throws(APIClient.HealthHistory.Failure::class)
    suspend fun history(): APIClient.HealthHistory.Response {
        var path = "/health/history"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<List<APIClient.HealthHistory.ResponseBodyItem>>(data.decodeToString())
                        return@use APIClient.HealthHistory.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.HealthHistory.Failure.Decoding(error, statusCode, data) }
                }
                else -> throw APIClient.HealthHistory.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }
}

class APINotificationsClient(private val client: OkHttpClient, private val baseUrl: String, private val json: Json, private val requestContextHeaders: Map<String, String>, private val requestInterceptor: (suspend (Request.Builder) -> Unit)?, private val responseInterceptor: (suspend (Request, Response) -> Unit)?) {

    /** Send a notification (discriminated by channel) */
    @Throws(APIClient.NotificationsSendNotification.Failure::class)
    suspend fun sendNotification(build: APIClient.NotificationsSendNotification.Scope.() -> APIClient.NotificationsSendNotification.Args): APIClient.NotificationsSendNotification.Response {
        val args = APIClient.NotificationsSendNotification.Scope.build()
        val body = args.body
        var path = "/notifications"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBody: RequestBody? = null
        requestBody = json.encodeToString(body.payload).toRequestBody("application/json".toMediaType())
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("POST", requestBody)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                202 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.NotificationsSendNotification.Response202>(data.decodeToString())
                        return@use APIClient.NotificationsSendNotification.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.NotificationsSendNotification.Failure.Decoding(error, statusCode, data) }
                }
                400 -> {
                    val payload = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.NotificationsSendNotification.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.NotificationsSendNotification.Failure.BadRequest(body = payload)
                }
                else -> throw APIClient.NotificationsSendNotification.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** List events — exercises Date / enum / array query params */
    @Throws(APIClient.NotificationsListEvents.Failure::class)
    suspend fun listEvents(build: APIClient.NotificationsListEvents.Scope.() -> APIClient.NotificationsListEvents.Args = { query() }): APIClient.NotificationsListEvents.Response {
        val args = APIClient.NotificationsListEvents.Scope.build()
        val query = args.query ?: APIClient.NotificationsListEvents.Query()
        var path = "/events"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        if (query.since != null) {
            for (stringValue in Kizuna.stringifyQueryValue(query.since)) {
                urlBuilder.addQueryParameter("since", stringValue)
            }
        }
        if (query.kind != null) {
            for (stringValue in Kizuna.stringifyQueryValue(query.kind)) {
                urlBuilder.addQueryParameter("kind", stringValue)
            }
        }
        if (query.ids != null) {
            for (stringValue in Kizuna.stringifyQueryValue(query.ids)) {
                urlBuilder.addQueryParameter("ids", stringValue)
            }
        }
        if (query.label != null) {
            for (stringValue in Kizuna.stringifyQueryValue(query.label)) {
                urlBuilder.addQueryParameter("label", stringValue)
            }
        }
        if (query.tagIds != null) {
            for (stringValue in Kizuna.stringifyQueryValue(query.tagIds)) {
                urlBuilder.addQueryParameter("tagIds", stringValue)
            }
        }
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.NotificationsListEvents.ResponseBody>(data.decodeToString())
                        return@use APIClient.NotificationsListEvents.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.NotificationsListEvents.Failure.Decoding(error, statusCode, data) }
                }
                400 -> {
                    val payload = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.NotificationsListEvents.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.NotificationsListEvents.Failure.BadRequest(body = payload)
                }
                else -> throw APIClient.NotificationsListEvents.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Validate contract — exercises generator bug coverage */
    @Throws(APIClient.NotificationsValidateConfig.Failure::class)
    suspend fun validateConfig(build: APIClient.NotificationsValidateConfig.Scope.() -> APIClient.NotificationsValidateConfig.Args): APIClient.NotificationsValidateConfig.Response {
        val args = APIClient.NotificationsValidateConfig.Scope.build()
        val body = args.body
        var path = "/contract/validate"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBody: RequestBody? = null
        val payload = APIClient.NotificationsValidateConfig.Input(default = body.default, interval = body.interval)
        requestBody = json.encodeToString(payload).toRequestBody("application/json".toMediaType())
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("POST", requestBody)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.NotificationsValidateConfig.ResponseBody>(data.decodeToString())
                        return@use APIClient.NotificationsValidateConfig.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.NotificationsValidateConfig.Failure.Decoding(error, statusCode, data) }
                }
                400 -> {
                    val badRequest = try {
                        json.decodeFromString<API.ProblemDetails>(data.decodeToString())
                    } catch (_: Exception) { null }
                    if (badRequest != null) throw APIClient.NotificationsValidateConfig.Failure.BadRequest(body = badRequest)
                    val validationError = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (_: Exception) { null }
                    if (validationError != null) throw APIClient.NotificationsValidateConfig.Failure.ValidationError(body = validationError)
                    throw APIClient.NotificationsValidateConfig.Failure.Unexpected(statusCode = statusCode, data = data)
                }
                401 -> {
                    throw APIClient.NotificationsValidateConfig.Failure.Unauthorized
                }
                else -> throw APIClient.NotificationsValidateConfig.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Receive arbitrary webhook payload — exercises z.any() / AnyCodable codegen */
    @Throws(APIClient.NotificationsWebhook.Failure::class)
    suspend fun webhook(build: APIClient.NotificationsWebhook.Scope.() -> APIClient.NotificationsWebhook.Args): APIClient.NotificationsWebhook.Response {
        val args = APIClient.NotificationsWebhook.Scope.build()
        val body = args.body
        var path = "/webhook"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBody: RequestBody? = null
        requestBody = json.encodeToString(body.payload).toRequestBody("application/json".toMediaType())
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("POST", requestBody)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.NotificationsWebhook.ResponseBody>(data.decodeToString())
                        return@use APIClient.NotificationsWebhook.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.NotificationsWebhook.Failure.Decoding(error, statusCode, data) }
                }
                400 -> {
                    val payload = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.NotificationsWebhook.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.NotificationsWebhook.Failure.BadRequest(body = payload)
                }
                else -> throw APIClient.NotificationsWebhook.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }
}

class APIMembersClient(private val client: OkHttpClient, private val baseUrl: String, private val json: Json, private val requestContextHeaders: Map<String, String>, private val requestInterceptor: (suspend (Request.Builder) -> Unit)?, private val responseInterceptor: (suspend (Request, Response) -> Unit)?) {

    /** List workspace members */
    @Throws(APIClient.MembersListMembers.Failure::class)
    suspend fun listMembers(): APIClient.MembersListMembers.Response {
        var path = "/workspace/members"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.MembersListMembers.ResponseBody>(data.decodeToString())
                        return@use APIClient.MembersListMembers.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.MembersListMembers.Failure.Decoding(error, statusCode, data) }
                }
                else -> throw APIClient.MembersListMembers.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Invite a member to the workspace */
    @Throws(APIClient.MembersInviteMember.Failure::class)
    suspend fun inviteMember(build: APIClient.MembersInviteMember.Scope.() -> APIClient.MembersInviteMember.Args): APIClient.MembersInviteMember.Response {
        val args = APIClient.MembersInviteMember.Scope.build()
        val body = args.body
        var path = "/workspace/members"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBody: RequestBody? = null
        val payload = APIClient.MembersInviteMember.Input(email = body.email)
        requestBody = json.encodeToString(payload).toRequestBody("application/json".toMediaType())
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("POST", requestBody)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                201 -> {
                    try {
                        val payload = json.decodeFromString<API.User>(data.decodeToString())
                        return@use APIClient.MembersInviteMember.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.MembersInviteMember.Failure.Decoding(error, statusCode, data) }
                }
                409 -> {
                    val payload = try {
                        json.decodeFromString<API.ProblemDetails>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.MembersInviteMember.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.MembersInviteMember.Failure.Conflict(body = payload)
                }
                400 -> {
                    val payload = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.MembersInviteMember.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.MembersInviteMember.Failure.BadRequest(body = payload)
                }
                else -> throw APIClient.MembersInviteMember.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }
}

class APIWorkspaceClient(private val client: OkHttpClient, private val baseUrl: String, private val json: Json, private val requestContextHeaders: Map<String, String>, private val requestInterceptor: (suspend (Request.Builder) -> Unit)?, private val responseInterceptor: (suspend (Request, Response) -> Unit)?) {

    /** Get workspace info */
    @Throws(APIClient.WorkspaceGetWorkspace.Failure::class)
    suspend fun getWorkspace(): APIClient.WorkspaceGetWorkspace.Response {
        var path = "/workspace"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.WorkspaceGetWorkspace.ResponseBody>(data.decodeToString())
                        return@use APIClient.WorkspaceGetWorkspace.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.WorkspaceGetWorkspace.Failure.Decoding(error, statusCode, data) }
                }
                else -> throw APIClient.WorkspaceGetWorkspace.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Delete the workspace — owner-only via the auth map */
    @Throws(APIClient.WorkspaceDeleteWorkspace.Failure::class)
    suspend fun deleteWorkspace(): APIClient.WorkspaceDeleteWorkspace.Response {
        var path = "/workspace"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("DELETE", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.WorkspaceDeleteWorkspace.ResponseBody>(data.decodeToString())
                        return@use APIClient.WorkspaceDeleteWorkspace.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.WorkspaceDeleteWorkspace.Failure.Decoding(error, statusCode, data) }
                }
                else -> throw APIClient.WorkspaceDeleteWorkspace.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Transfer ownership — owner-only via the auth map */
    @Throws(APIClient.WorkspaceTransfer.Failure::class)
    suspend fun transfer(build: APIClient.WorkspaceTransfer.Scope.() -> APIClient.WorkspaceTransfer.Args): APIClient.WorkspaceTransfer.Response {
        val args = APIClient.WorkspaceTransfer.Scope.build()
        val body = args.body
        var path = "/workspace/transfer"
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBody: RequestBody? = null
        val payload = APIClient.WorkspaceTransfer.Input(toUserId = body.toUserId)
        requestBody = json.encodeToString(payload).toRequestBody("application/json".toMediaType())
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("POST", requestBody)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.WorkspaceTransfer.ResponseBody>(data.decodeToString())
                        return@use APIClient.WorkspaceTransfer.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.WorkspaceTransfer.Failure.Decoding(error, statusCode, data) }
                }
                400 -> {
                    val payload = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.WorkspaceTransfer.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.WorkspaceTransfer.Failure.BadRequest(body = payload)
                }
                else -> throw APIClient.WorkspaceTransfer.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }
}

class APIInvitesClient(private val client: OkHttpClient, private val baseUrl: String, private val json: Json, private val requestContextHeaders: Map<String, String>, private val requestInterceptor: (suspend (Request.Builder) -> Unit)?, private val responseInterceptor: (suspend (Request, Response) -> Unit)?) {

    /** Resolve an invite by its capability-URL token, guarded by a custom path-token identity */
    @Throws(APIClient.InvitesGetInvite.Failure::class)
    suspend fun getInvite(build: APIClient.InvitesGetInvite.Scope.() -> APIClient.InvitesGetInvite.Args): APIClient.InvitesGetInvite.Response {
        val args = APIClient.InvitesGetInvite.Scope.build()
        val params = args.params
        var path = "/invites/:token"
        path = path.replace(":token", Kizuna.encodePathSegment(params.token))
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("GET", null)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                200 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.InvitesGetInvite.ResponseBody>(data.decodeToString())
                        return@use APIClient.InvitesGetInvite.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.InvitesGetInvite.Failure.Decoding(error, statusCode, data) }
                }
                404 -> {
                    val payload = try {
                        json.decodeFromString<API.ProblemDetails>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.InvitesGetInvite.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.InvitesGetInvite.Failure.NotFound(body = payload)
                }
                else -> throw APIClient.InvitesGetInvite.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }

    /** Accept an invite via the capability URL */
    @Throws(APIClient.InvitesAcceptInvite.Failure::class)
    suspend fun acceptInvite(build: APIClient.InvitesAcceptInvite.Scope.() -> APIClient.InvitesAcceptInvite.Args): APIClient.InvitesAcceptInvite.Response {
        val args = APIClient.InvitesAcceptInvite.Scope.build()
        val params = args.params
        val body = args.body
        var path = "/invites/:token/accept"
        path = path.replace(":token", Kizuna.encodePathSegment(params.token))
        val urlBuilder = Kizuna.resolveUrl(baseUrl, path)
        var requestBody: RequestBody? = null
        val payload = APIClient.InvitesAcceptInvite.Input(name = body.name)
        requestBody = json.encodeToString(payload).toRequestBody("application/json".toMediaType())
        var requestBuilder = Request.Builder()
            .url(urlBuilder.build())
            .method("POST", requestBody)
        for ((name, value) in requestContextHeaders) requestBuilder = requestBuilder.header(name, value)
        requestInterceptor?.invoke(requestBuilder)
        val httpResponse = Kizuna.execute(client, requestBuilder.build())
        return httpResponse.use {
            responseInterceptor?.invoke(requestBuilder.build(), httpResponse)
            val data = kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) { httpResponse.body?.bytes() ?: ByteArray(0) }
            val statusCode = httpResponse.code
            when (statusCode) {
                201 -> {
                    try {
                        val payload = json.decodeFromString<APIClient.InvitesAcceptInvite.Response201>(data.decodeToString())
                        return@use APIClient.InvitesAcceptInvite.Response(body = payload)
                    }
                    catch (error: Exception) { throw APIClient.InvitesAcceptInvite.Failure.Decoding(error, statusCode, data) }
                }
                404 -> {
                    val payload = try {
                        json.decodeFromString<API.ProblemDetails>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.InvitesAcceptInvite.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.InvitesAcceptInvite.Failure.NotFound(body = payload)
                }
                400 -> {
                    val payload = try {
                        json.decodeFromString<APIClient.ValidationError>(data.decodeToString())
                    } catch (error: Exception) { throw APIClient.InvitesAcceptInvite.Failure.Decoding(error, statusCode, data) }
                    throw APIClient.InvitesAcceptInvite.Failure.BadRequest(body = payload)
                }
                else -> throw APIClient.InvitesAcceptInvite.Failure.Unexpected(statusCode = statusCode, data = data)
            }
        }
    }
}

private object Kizuna {
    fun resolveUrl(baseUrl: String, path: String): HttpUrl.Builder {
        val base = baseUrl.toHttpUrl()
        val trimmedPath = path.trimStart('/')
        val basePath = base.encodedPath.trimEnd('/')
        val fullPath = if (basePath.isEmpty()) "/$trimmedPath" else "$basePath/$trimmedPath"
        return base.newBuilder().encodedPath(fullPath)
    }

    fun encodePathSegment(value: String): String {
        return java.net.URLEncoder.encode(value, "UTF-8").replace("+", "%20")
    }

    fun stringifyQueryValue(value: Any): List<String> {
        return when (value) {
            is Instant -> listOf(value.toString())
            is List<*> -> value.filterNotNull().flatMap { stringifyQueryValue(it) }
            is KizunaQueryValue -> listOf(value.wireValue)
            is Enum<*> -> listOf(value.name)
            else -> listOf(value.toString())
        }
    }

    suspend fun execute(client: OkHttpClient, request: Request): Response {
        return kotlinx.coroutines.suspendCancellableCoroutine { continuation ->
            val call = client.newCall(request)
            continuation.invokeOnCancellation {
                call.cancel()
            }
            call.enqueue(object : Callback {
                override fun onFailure(call: Call, e: java.io.IOException) {
                    continuation.resumeWith(Result.failure(e))
                }
                override fun onResponse(call: Call, response: Response) {
                    continuation.resumeWith(Result.success(response))
                }
            }
            )
        }
    }
}
